[[datasets]]
  enable_bucket = true
  bucket_no_upscale = true
  resolution = [800, 1162]
  min_bucket_reso = 256
  max_bucket_reso = 1162
  batch_size = 1

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/bodre/selected_01'
  caption_extension = '.txt'
  class_tokens = 'bodre'
  num_repeats = 20
  shuffle_caption = true
