[[datasets]]
  enable_bucket = true
  bucket_no_upscale = true
  resolution = [1024, 1152]
  min_bucket_reso = 256
  max_bucket_reso = 1152
  batch_size = 1

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/bodre/'
  caption_extension = '.txt'
  class_tokens = 'bodre'
  num_repeats = 10
  shuffle_caption = true


[[datasets]]
  enable_bucket = true
  bucket_no_upscale = true
  resolution = [512, 768]
  min_bucket_reso = 256
  max_bucket_reso = 1024
  batch_size = 1

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/bodre/'
  caption_extension = '.txt'
  class_tokens = 'bodre'
  num_repeats = 10
  shuffle_caption = true