[[datasets]]
  enable_bucket = true
  bucket_no_upscale = true
  resolution = [512, 512]
  min_bucket_reso = 256
  max_bucket_reso = 512
  batch_size = 10

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/bodre/'
  caption_extension = '.txt'
  class_tokens = 'bodre'
  num_repeats = 20
  shuffle_caption = true


[[datasets]]
  enable_bucket = true
  bucket_no_upscale = true
  resolution = [768, 768]
  min_bucket_reso = 256
  max_bucket_reso = 1024
  batch_size = 10

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/bodre/'
  caption_extension = '.txt'
  class_tokens = 'bodre'
  num_repeats = 20
  shuffle_caption = true