pretrained_model_name_or_path = "/home/admin/models/models/v1-5-pruned-emaonly.safetensors"
caption_extension = ".txt"
cache_latents = false
output_dir = "/home/admin/github/showMan/training/output/bodre_network"
output_name = "bodre"
save_precision = "fp16"
save_model_as = "safetensors"
save_every_n_epochs = 5
sample_every_n_epochs = 5
train_batch_size = 1


seed = 1234
clip_skip = 1
max_token_length = 225
xformers = true
max_train_epochs = 100
persistent_data_loader_workers = true
gradient_checkpointing = true
gradient_accumulation_steps = 1
mixed_precision = "fp16"
logging_dir = "/home/admin/github/showMan/training/log/bodre_network"
sample_prompts = "/home/admin/github/showMan/training/bodre/prompt.txt"
sample_sampler = "euler_a"
optimizer_type = "AdamW8bit"
learning_rate = 1.6e-4
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 100
lr_scheduler_num_cycles = 4
dataset_config = "/home/admin/github/showMan/training/bodre/dataset_config.toml"
unet_lr = 1.6e-4
text_encoder_lr = 4e-5
multires_noise_iterations = 6
multires_noise_discount = 0.1
stop_text_encoder_training = 1000
network_module = "lycoris.kohya"
network_dim = 32
network_alpha = 16
network_args = [ "algo=loha", "conv_dim=32", "conv_alpha=16", "unit=4" ]


