pretrained_model_name_or_path = "/home/admin/models/duitang/beautiful_realistic_asians_v6.0.safetensors"
logging_dir = "/home/admin/github/showMan/training/log/bodre_network"
sample_prompts = "/home/admin/github/showMan/training/bodre/prompt.txt"
dataset_config = "/home/admin/github/showMan/training/bodre/dataset_config.toml"
output_dir = "/home/admin/github/showMan/training/output/bodre_network"
output_name = "bodre"
save_model_as = "safetensors"
caption_extension = ".txt"
xformers = true
save_precision = "fp16"
mixed_precision = "fp16"
cache_latents = false
save_every_n_epochs = 2
sample_every_n_epochs = 2
gradient_accumulation_steps = 2
network_train_unet_only = false
network_train_text_encoder_only = false

seed = 1234
clip_skip = 1
max_token_length = 225
max_train_epochs = 100
persistent_data_loader_workers = true
gradient_checkpointing = true
sample_sampler = "euler_a"
optimizer_type = "AdamW8bit"
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 100
lr_scheduler_num_cycles = 0
learning_rate = 1.6e-4
unet_lr = 1.6e-4
text_encoder_lr = 5e-5
multires_noise_iterations = 6
multires_noise_discount = 0.1
stop_text_encoder_training = 2000
network_module = "lycoris.kohya"
network_dim = 32
network_alpha = 16
network_args = [ "algo=loha", "conv_dim=32", "conv_alpha=16", "unit=4" ]


