[[datasets]]
  enable_bucket = true
  resolution = 1024
  bucket_no_upscale = true
  min_bucket_reso = 256
  max_bucket_reso = 1024
  # sdxl 此值需要是 32 倍数
  bucket_reso_steps = 32
  batch_size = 1

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/${INSTANCE}/'
  caption_extension = '.txt'
  class_tokens = '${INSTANCE}'
  num_repeats = 30
  shuffle_caption = false