pretrained_model_name_or_path = "/root/models/models/sdXL_v10.safetensors"
logging_dir = "/home/admin/github/showMan/training/log/sdxl_${INSTANCE}_network"
sample_prompts = "/home/admin/github/showMan/training/${INSTANCE}/prompt.txt"
dataset_config = "/home/admin/github/showMan/training/${INSTANCE}/sdxl_dataset_config.toml"
output_dir = "/home/admin/github/showMan/training/output/sdxl_${INSTANCE}_network"
output_name = "${INSTANCE}"
save_model_as = "safetensors"
caption_extension = ".txt"
xformers = true
no_half_vae = true
save_precision = "bf16"
mixed_precision = "bf16"
cache_latents = false
save_every_n_epochs = 1
sample_every_n_epochs = 1
gradient_accumulation_steps = 1
network_train_unet_only = false
network_train_text_encoder_only = false


seed = 1234
max_token_length = 75
max_train_epochs = 100
persistent_data_loader_workers = true
gradient_checkpointing = true
sample_sampler = "euler_a"
optimizer_type = "AdaFactor"
lr_scheduler = "cosine"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 0
learning_rate = 4e-4
unet_lr = 4e-4
text_encoder_lr = 4e-4
multires_noise_iterations = 8
multires_noise_discount = 0.2
stop_text_encoder_training = 2000
network_module = "networks.lora"
network_dim = 256
network_alpha = 1
#network_args = [ "conv_dim=32", "unit=4", "down_lr_weight=1,0.2,1,1,0.2,1,1,0.2,1,1,1,1", "mid_lr_weight=1", "up_lr_weight=1,1,1,1,1,1,1,1,1,1,1,1", "block_dims=32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32", "block_alphas=4,4,8,4,8,8,8,4,4,8,8,8  ,4,  8,4,8,4,4,4,8,4,4,4,8,4", "conv_block_dims=8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8", "conv_block_alpha=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1",]


