pretrained_model_name_or_path = "/home/admin/models/models/v1-5-pruned-emaonly.safetensors"
logging_dir = "/home/admin/github/showMan/training/log/${INSTANCE}_network"
sample_prompts = "/home/admin/github/showMan/training/${INSTANCE}/prompt.txt"
dataset_config = "/home/admin/github/showMan/training/${INSTANCE}/dataset_config.toml"
output_dir = "/home/admin/github/showMan/training/output/${INSTANCE}_network"
output_name = "${INSTANCE}"
save_model_as = "safetensors"
caption_extension = ".txt"
xformers = true
save_precision = "fp16"
mixed_precision = "fp16"
resolution = "512,512"
cache_latents = true
save_every_n_epochs = 5
sample_every_n_epochs = 5
train_batch_size = 3
gradient_accumulation_steps = 2
network_train_unet_only = false
network_train_text_encoder_only = false

seed = 1234
clip_skip = 1
max_token_length = 225
max_train_epochs = 100
persistent_data_loader_workers = true
gradient_checkpointing = true
sample_sampler = "euler_a"
optimizer_type = "AdamW8bit"
lr_scheduler = "cosine"
lr_warmup_steps = 100
lr_scheduler_num_cycles = 0
learning_rate = 2e-4
unet_lr = 2e-4
text_encoder_lr = 1e-4
multires_noise_iterations = 8
multires_noise_discount = 0.2
stop_text_encoder_training = 2000
network_module = "networks.dylora"
network_dim = 32
network_alpha = 16
network_args = [ "conv_dim=32", "unit=4", "down_lr_weight=1,0.2,1,1,0.2,1,1,0.2,1,1,1,1", "mid_lr_weight=1", "up_lr_weight=1,1,1,1,1,1,1,1,1,1,1,1", "block_dims=32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32", "block_alphas=4,4,8,4,8,8,8,4,4,8,8,8  ,4,  8,4,8,4,4,4,8,4,4,4,8,4", "conv_block_dims=8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8", "conv_block_alpha=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1",]


