[[datasets]]
  enable_bucket = true
  bucket_no_upscale = true
  min_bucket_reso = 256
  max_bucket_reso = 1024
  batch_size = 11

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/lves/'
  caption_extension = '.txt'
  class_tokens = 'lves'
  num_repeats = 40
  shuffle_caption = true


  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/bodre/'
  caption_extension = '.txt'
  class_tokens = 'bodre'
  num_repeats = 20
  shuffle_caption = true