[[datasets]]
  enable_bucket = true
  resolution = [768, 1024]
  bucket_no_upscale = true
  min_bucket_reso = 256
  max_bucket_reso = 1024
  batch_size = 6

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/haoyue/'
  caption_extension = '.txt'
  class_tokens = 'haoyue'
  num_repeats = 5
  shuffle_caption = true