[[datasets]]
  enable_bucket = true
  resolution = [512, 768]
  bucket_no_upscale = true
  min_bucket_reso = 256
  max_bucket_reso = 768
  batch_size = 1

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/jiga/'
  caption_extension = '.txt'
  class_tokens = 'jiga'
  num_repeats = 20
  shuffle_caption = true

[[datasets]]
  enable_bucket = true
  resolution = [768, 1152]
  bucket_no_upscale = true
  min_bucket_reso = 256
  max_bucket_reso = 1152
  batch_size = 1

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/jiga/'
  caption_extension = '.txt'
  class_tokens = 'jiga'
  num_repeats = 20
  shuffle_caption = true


[[datasets]]
  enable_bucket = true
  resolution = [1024, 1536]
  bucket_no_upscale = true
  min_bucket_reso = 256
  max_bucket_reso = 1536
  batch_size = 1

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/jiga/'
  caption_extension = '.txt'
  class_tokens = 'jiga'
  num_repeats = 20
  shuffle_caption = true