[[datasets]]
  enable_bucket = true
  resolution = [1024, 1536]
  bucket_no_upscale = true
  min_bucket_reso = 1024
  max_bucket_reso = 1536
  batch_size = 2

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/jiga/'
  caption_extension = '.txt'
  class_tokens = 'jiga'
  num_repeats = 30
  shuffle_caption = true