pretrained_model_name_or_path = "/home/admin/models/models/v1-5-pruned-emaonly.safetensors"
caption_extension = ".txt"
resolution = "512,512"
cache_latents = false
output_dir = "/home/admin/github/showMan/training/output/ldh_network"
output_name = "ldh"
save_precision = "fp16"
save_model_as = "safetensors"
save_every_n_epochs = 5
sample_every_n_epochs = 5
train_batch_size = 3


seed = 1234
clip_skip = 2
max_token_length = 225
xformers = true
max_train_epochs = 100
persistent_data_loader_workers = true
gradient_checkpointing = true
gradient_accumulation_steps = 2
mixed_precision = "fp16"
logging_dir = "/home/admin/github/showMan/training/log/ldh_network"
sample_prompts = "/home/admin/github/showMan/training/ldh/prompt.txt"
sample_sampler = "euler_a"
optimizer_type = "AdamW8bit"
learning_rate = 2e-4
lr_scheduler = "constant"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 0
dataset_config = "/home/admin/github/showMan/training/ldh/dataset_config.toml"
unet_lr = 2e-4
text_encoder_lr = 1e-4
multires_noise_iterations = 6
multires_noise_discount = 0.1
stop_text_encoder_training = 100
network_module = "networks.dylora"
network_dim = 32
network_alpha = 16
network_args = [ "conv_dim=32", "unit=4", "down_lr_weight=0,0,0,0,0,1.0,1.0,1.0,1.0,1.0,1.0,1.5", "mid_lr_weight=2.0", "up_lr_weight=1.5,1.5,1.5,1.5,1.0,1.0,1.0,0,0,0,0,0", "block_dims=2,4,4,4,8,8,8,8,12,12,12,12,16,12,12,12,12,8,8,8,8,4,4,4,2", "block_alphas=2,2,2,2,4,4,4,4,6,6,6,6,8,6,6,6,6,4,4,4,4,2,2,2,2",]


