[[datasets]]
  enable_bucket = true
  resolution = [512, 512]
  bucket_no_upscale = true
  min_bucket_reso = 256
  max_bucket_reso = 1024
  batch_size = 4

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/denlash/'
  caption_extension = '.txt'
  class_tokens = 'denlash'
  num_repeats = 20
  shuffle_caption = true