[[datasets]]
  enable_bucket = true
  resolution = 1024
  bucket_no_upscale = true
  min_bucket_reso = 1024
  max_bucket_reso = 1024
  batch_size = 2

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/danyanpi/selected_02'
  caption_extension = '.txt'
  class_tokens = 'danyanpi'
  num_repeats = 10
  shuffle_caption = true



# [[datasets]]
#   enable_bucket = true
#   resolution = [768, 1364]
#   bucket_no_upscale = true
#   min_bucket_reso = 256
#   max_bucket_reso = 1364
#   batch_size = 3

#   [[datasets.subsets]]
#   image_dir = '/home/admin/github/showMan/saved/danyanpi/'
#   caption_extension = '.txt'
#   class_tokens = 'danyanpi'
#   num_repeats = 10
#   shuffle_caption = true

#   [[datasets.subsets]]
#   image_dir = '/home/admin/github/class/sd_girl_512_682_400'
#   is_reg = true
#   class_tokens = 'girl'
#   caption_extension = '.txt'
#   num_repeats = 1
#   shuffle_caption = false

