[[datasets]]
  enable_bucket = true
  resolution = [512, 682]
  bucket_no_upscale = true
  min_bucket_reso = 256
  max_bucket_reso = 1024
  batch_size = 5

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/danyanpi/'
  caption_extension = '.txt'
  class_tokens = 'danyanpi'
  num_repeats = 10
  shuffle_caption = true

  [[datasets.subsets]]
  image_dir = '/home/admin/github/class/bra_girl_512_682'
  is_reg = true
  class_tokens = 'girl'
  caption_extension = '.txt'
  num_repeats = 1
  shuffle_caption = false