[[datasets]]
  enable_bucket = true
  resolution = 1024
  bucket_no_upscale = true
  min_bucket_reso = 512
  max_bucket_reso = 1024
  # sdxl 此值需要是 32 倍数
  bucket_reso_steps = 32
  batch_size = 3

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/danyanpi/selected_01'
  caption_extension = '.txt'
  class_tokens = 'danyanpi'
  num_repeats = 20
  shuffle_caption = false


