[[datasets]]
  enable_bucket = true
  resolution = 1024
  bucket_no_upscale = true
  min_bucket_reso = 512
  max_bucket_reso = 1024
  # sdxl 此值不能是 16
  bucket_reso_steps = 64
  batch_size = 1

  [[datasets.subsets]]
  image_dir = '/home/admin/github/showMan/saved/danyanpi/selected_01'
  caption_extension = '.txt'
  class_tokens = 'danyanpi'
  num_repeats = 10
  shuffle_caption = false


# [[datasets]]
#   enable_bucket = true
#   resolution = [768, 1364]
#   bucket_no_upscale = true
#   min_bucket_reso = 256
#   max_bucket_reso = 1364
#   batch_size = 3

#   [[datasets.subsets]]
#   image_dir = '/home/admin/github/showMan/saved/danyanpi/'
#   caption_extension = '.txt'
#   class_tokens = 'danyanpi'
#   num_repeats = 10
#   shuffle_caption = true


