pretrained_model_name_or_path = "/home/admin/models/models/v1-5-pruned-emaonly.safetensors"
logging_dir = "/home/admin/github/showMan/training/log/danyanpi_network"
sample_prompts = "/home/admin/github/showMan/training/danyanpi/prompt.txt"
dataset_config = "/home/admin/github/showMan/training/danyanpi/dataset_config.toml"
output_dir = "/home/admin/github/showMan/training/output/danyanpi_network"
output_name = "danyanpi"
save_model_as = "safetensors"
caption_extension = ".txt"
xformers = true
save_precision = "fp16"
mixed_precision = "fp16"
cache_latents = false
save_every_n_epochs = 1
sample_every_n_epochs = 1
gradient_accumulation_steps = 1


seed = 1234
clip_skip = 1
max_token_length = 225
max_train_epochs = 100
persistent_data_loader_workers = true
gradient_checkpointing = true
sample_sampler = "euler_a"
optimizer_type = "AdamW8bit"
lr_scheduler = "constant"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 0
learning_rate = 1.8e-4
unet_lr = 1.8e-4
text_encoder_lr = 4e-5
# multires_noise_iterations = 6
# multires_noise_discount = 0.1
network_module = "networks.lora"
network_dim = 32
network_alpha = 16
#network_args = [ "conv_dim=32", "unit=4", "down_lr_weight=1,0.2,1,1,0.2,1,1,0.2,1,1,1,1", "mid_lr_weight=1", "up_lr_weight=1,1,1,1,1,1,1,1,1,1,1,1", "block_dims=32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32", "block_alphas=4,4,8,4,8,8,8,4,4,8,8,8  ,4,  8,4,8,4,4,4,8,4,4,4,8,4", "conv_block_dims=8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8", "conv_block_alpha=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1",]

